"use strict";

module.exports = [
  "/",
  "/about",
  "/docs",
  "/docs/victory-animation",
  "/docs/victory-area",
  "/docs/victory-axis",
  "/docs/victory-bar",
  "/docs/victory-candlestick",
  "/docs/victory-chart",
  "/docs/victory-clip-container",
  "/docs/victory-container",
  "/docs/victory-errorbar",
  "/docs/victory-group",
  "/docs/victory-label",
  "/docs/victory-line",
  "/docs/victory-pie",
  "/docs/victory-portal",
  "/docs/victory-primitives",
  "/docs/victory-scatter",
  "/docs/victory-shared-events",
  "/docs/victory-stack",
  "/docs/victory-theme",
  "/docs/victory-tooltip",
  "/docs/victory-transition",
  "/docs/victory-voronoi",
  "/docs/victory-voronoi-tooltip",
  // "/recipes",
  // "/recipes/custom-central-axis",
  // "/recipes/custom-data-component",
  // "/recipes/custom-styles",
  // "/recipes/multiple-axes",
  // "/recipes/candlestick-dashboard",
  // "/recipes/tooltip",
  // "/recipes/shared-events",
  // "/recipes/theme-park",
  "/guides",
  "/guides/custom-central-axis",
  "/guides/custom-data-component",
  "/guides/custom-styles",
  "/guides/multiple-axes",
  "/guides/candlestick-dashboard",
  "/guides/tooltip",
  "/guides/shared-events",
  "/guides/theme-park"
];
